### ISSUE TITLE
How to show "Updated on: Date"?

### ISSUE THREAD

**Issue by BigBoyBarney** [cotes2020/cotes-blog#1128]
Hi! First of all, thank you so much for this template. It's really cool, and I've had a lot of fun tinkering with it. I might PR a more extensive tutorial for the starter project in the near future :)

One thing I couldn't figure out is how to get the "Updated" date on the post.
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/86712892/0cea9af3-e39d-4252-a970-e9406343201c)

Based on what I found in [post.html](https://github.com/cotes2020/jekyll-theme-chirpy/blob/e8ef69ad1784661c5bb06dbcf530cfa37af63383/_layouts/post.html#L26), it should automatically update it if the last changed date does not match the date in the post, right? However, when I try the sample post in your site, I don't get that at all.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/86712892/14828548-ccaf-4d22-a1c0-6ca9e3ac881e)
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/86712892/e30e86d8-9b61-4154-9f9f-87ad5b029547)
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/86712892/63409ab4-6711-4bf9-a0e0-5e33778c855a)

Any help would be appreciated. 
Cheers
Barney

**Comment by NichtsHsu** [comment]
The updated date is generated from git:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/e8ef69ad1784661c5bb06dbcf530cfa37af63383/_plugins/posts-lastmod-hook.rb#L10
